# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'eBlink' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eBlink


  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'Firebase/Firestore', '~> 5.9.0'
  pod 'Firebase/Functions', '~> 5.9.0'
  pod 'Firebase/Messaging', '~> 5.9.0'
  pod 'Firebase/Storage', '~> 5.9.0'
  pod 'Firebase/AdMob', '~> 5.9.0'

  #pod 'CodePush', :path => '../node_modules/react-native-code-push'



  #pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  #pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  #pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'eBlinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eBlink-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eBlink-tvOS

  target 'eBlink-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
