# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core', '~> 5.3.0'

target 'eBlink' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eBlink


  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'eBlinkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eBlink-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eBlink-tvOS

  target 'eBlink-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
